version: "3.9"
services:
  go-app:
    build:
      context: .
    container_name: echoApp
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - keploy-network

  postgres:
        image: postgres:10.5
        container_name: postgresDb
        restart: always
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - '5432:5432'
        volumes: 
          # - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
          - keploy-network

networks:
    keploy-network: 
      external: false
