name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

        
      - name: Test
        run: |
            uname -a
            host localhost
            sudo -E env "PATH=$PATH" ./server test -c /home/runner/work/samples-go/samples-go/gin-mongo/test-app-url-shortener --delay 2
        env:
          ENABLE_DEDUP: true
          ENABLE_TELEMETRY: true
