name: Go-Sample-Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
jobs:
  keploy-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test-Report
      uses: keploy/testgpt@main
      with:
        working-directory: /gin-mongo
        delay: 10
        command: go run main.go handler.go